runtime: nodejs10

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 10.0s
  max_pending_latency: 15.0s

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto